require:
  - rubocop-performance
  - rubocop-rake

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    # uncomment if use rspec cops
    - "config/rspec.yml"
    - "config/performance.yml"

AllCops:
  TargetRubyVersion: 3.0
  # uncomment if use rails cops
  # TargetRailsVersion: 5.1
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/IndentationConsistency:
    EnforcedStyle: indented_internal_methods

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/ScriptPermission:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/pdf-reader.rb

Style/FetchEnvVar:
  Enabled: false
