# ref. https://cloud.google.com/appengine/docs/standard/ruby/config/appref

runtime: ruby30

entrypoint: ./appengine/entrypoint.sh

handlers:
  # Serve on Frontend server
  - url: /fonts
    static_dir: public/fonts
    secure: always

  - url: /javascripts
    static_dir: public/javascripts
    secure: always

  - url: /stylesheets
    static_dir: public/stylesheets
    secure: always

  - url: /favicon.ico
    static_files: public/favicon.ico
    upload: public/favicon.ico
    secure: always

  # Serve on App Server
  - url: /cron/.*
    script: auto
    secure: always
    login: admin

  - url: /.*
    script: auto
    secure: always

env_variables:
  RACK_ENV: production
  PUMA_WORKERS: 0
  MAX_THREADS: 8
  SENTRY_RELEASE: __GITHUB_SHA__

build_env_variables:
  RACK_ENV: production

instance_class: F1

automatic_scaling:
  max_instances: 1
  min_instances: 0
