version: 2.1

orbs:
  heroku: circleci/heroku@volatile
  slack:  circleci/slack@3

workflows:
  version: 2

  deploy:
    jobs:
      - heroku/deploy-via-git:
          context: Heroku
          filters:
            branches:
              only: heroku
          post-deploy:
            - slack/status
