version: 2.1

executors:
  default:
    docker:
      - image: alpine
    working_directory: ~/app

jobs:
  dummy:
    executor:
      name: default

    steps:
      - run: date

workflows:
  version: 2

  dummy:
    jobs:
      - dummy
