#!/bin/bash -xe

export DATABASE_URL=gcp:///DATABASE_URL
export SENTRY_DSN=gcp:///SENTRY_DSN
export TWITTER_ACCESS_TOKEN=gcp:///TWITTER_ACCESS_TOKEN
export TWITTER_ACCESS_TOKEN_SECRET=gcp:///TWITTER_ACCESS_TOKEN_SECRET
export TWITTER_CONSUMER_KEY=gcp:///TWITTER_CONSUMER_KEY
export TWITTER_CONSUMER_SECRET=gcp:///TWITTER_CONSUMER_SECRET
